name: leaf_and_quill_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  #firebase_setup
  firebase_core: ^2.28.0
  firebase_storage: ^11.7.0
  cloud_firestore: ^4.16.0
  firebase_auth: ^4.19.0
  google_sign_in: ^6.2.1

  #UI
  flutter_progress_hud: ^2.0.2
  fpdart: ^1.1.0
  image_picker: ^1.1.1
  flutter_riverpod: ^2.5.1
  routemaster: ^1.0.1
  shared_preferences: ^2.2.3
  any_link_preview: ^3.0.2
  uuid: ^4.4.0
  dotted_border: ^2.1.0
  file_picker: ^8.0.3
  timeago: ^3.6.1
  pull_to_refresh: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  cached_video_player: ^2.0.4
  flutter_sound: ^9.4.11
  audioplayers: ^6.0.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  swipe_to: ^1.0.2
  photo_view: ^0.15.0
  smooth_page_indicator: ^1.1.0
  

dev_dependencies:

  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

flutter pub run flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"

flutter_native_splash:
  android: true
  ios: true
  color: "#FFFFFF"
  image: "assets/images/app_logo.png"

  android_12: 
    color: "#FFFFFF"
    image: "assets/images/app_logo.png"


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 400
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600

